[project]
name = "algo-trading-server"
version = "0.1.0"
description = "Algo Trading Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arq>=0.25.0",
    "asyncer>=0.0.18",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.139.0",
    "fyers-apiv3>=3.1.14",
    "httpx>=0.28.0",
    "pandas>=3.0.3",
    "pydantic-settings>=2.14.2",
    "redis>=8.0.1",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.51.0",
]

[tool.fastapi]
entrypoint = "main:app"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
